CONFIG_GPIO=y
CONFIG_LOG=y

CONFIG_LED_SUBSYSTEM=y

CONFIG_LED_BLINK_SLEEP_1S=y

CONFIG_LED_ADVANCED=n
CONFIG_LED_BRIGHTNESS=50
CONFIG_LED_FADE_DURATION_MS=400

CONFIG_LED_DEBUGGING=n
CONFIG_LED_CUSTOM_BLINK=n

